#!/bin/sh

clear
echo "================================================================="
echo " Building APK containing answerfile and post-installation script "
echo "================================================================="
echo

cd $HOME/alpine.sh
abuild checksum

[ -n "$UPDATE_CHECKSUM_ONLY" ] && exit

abuild -r

echo
echo "=================================================================="
echo " Building custom Alpine Linux ISO containing the installation APK "
echo "=================================================================="
echo

$HOME/aports/scripts/mkimage.sh \
    --outdir $HOME/iso \
    --tag v$ALPINE_VERSION \
    --repository http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/main \
    --extra-repository $HOME/packages/builder \
    --profile custom
