#!/bin/sh

# this script performs the finishing touches required to make the system more
# usable

# NOTE: all functions prefixed with a underscore (_) are helper functions and
# shouldn't be considered as installation steps

# TODO: think of a way of supporting containerized wayland workspaces without
#       having to install a wayland-only dependency for keeping things minimal
#       (in this case, the dependency being "seatd")

# ------------------------------------------------------------------------------

# exit on errors
set -e

# displays a given message in a nicely formatted box
_infobox() {
	border_length=$(( ${#1} + 2 ))
	printf "\n${bold}%${border_length}s\n" | tr " " "="
	echo " $1 "
	printf "%${border_length}s${normal}\n\n" | tr " " "="
}

# comments out a list of given installation steps to avoid running them again on
# a subsequent execution of this script
_complete_steps() {
	for step in "$@"; do
		sed -i "s/^$step$/#$step/" "$0"
	done
}

# displays a welcome message specifying a summary of actions that will be
# performed by the script, and prompt the user for confirmation to proceed with
# the post-installation process
welcome() {
    export USER_NAME=$(cat /etc/group | grep wheel | cut -d : -f 4 | cut -d , -f 2)
    clear
    echo "This post-installation script will perform the following tasks:"
    echo "- Install a set of essential packages"
    echo "- Setup non-root user ($USER_NAME) password, and add it to the 'docker' group"
    echo "- Replace 'mdev' with 'eudev'"
    echo "- Enable 'seatd' service to run at boot (and start it)"
    echo "- Enable the Docker service to run at boot (and start it)"
    echo
    read -rp "Proceed? (y/N) " proceed
    if echo "$proceed" | grep -vE "^[yY]$"; then
        exit
    fi
}

# installs a set of packages to make the system more usable
# ---------------------------------------------------------
# docker -> run containerized applications from "docker-experiment"
# git -> create and clone git repositories
# make -> create and run tasks from Makefiles (required by "docker-experiment")
# eudev -> replaces "mdev" with proper support for keyboard and mouse on Xorg
# seatd -> required for running wayland compositors
# alsa-utils -> provides "alsamixer" which is used to control the audio volume
# pulseaudio -> required to make the audio work properly
# pulseaudio-utils -> provides "pactl" which is used to generate "pulseaudio"
#                     shared sockets to be used in containerized applications
# udev-init-scripts -> required for udev to work
# udev-init-scripts-openrc -> required for udev to work
install_essential_packages() {
    _infobox "Installing essential packages"
    apk add docker git make eudev seatd alsa-utils pulseaudio pulseaudio-utils udev-init-scripts udev-init-scripts-openrc

    _complete_steps install_essential_packages
}

# set the non-root user password
# create the non-root user directory
# add the non-root user to the 'docker' group (allowing to run docker commands)
setup_user() {
    _infobox "Setting up '$USER_NAME' password"
    passwd "$USER_NAME"

    # for some strange reason, user directories created with setup-user doesn't
    # persist reboot
    _infobox "Creating '$USER_NAME' user directory at '/home/$USER_NAME'"
    mkdir -p /home/$USER_NAME
    chown -R $USER_NAME:$USER_NAME /home/$USER_NAME

    _infobox "Adding '$USER_NAME' to the 'docker' group"
    addgroup "$USER_NAME" docker

    _complete_steps setup_user
}

# disables "mdev" and delete it's service from openrc
# mouse and keyboard don't work properly on Xorg with "mdev", "eudev" is
# required
disable_mdev() {
    rc-service -s mdev stop
    rc-update delete mdev sysinit

    _complete_steps disable_mdev
}

# enables "eudev" and it's services
enable_eudev() {
    rc-update add udev sysinit
    rc-update add udev-trigger sysinit
    rc-update add udev-settle sysinit
    rc-update add udev-postmount default
    rc-service udev start

    _complete_steps enable_eudev
}

# enables "seatd" in order to run wayland compositors
enable_seatd() {
    _infobox "Enabling seatd service to run on boot"
    rc-update add seatd
    rc-service seatd start

    _complete_steps enable_seatd
}

# enables docker service to run on boot and starts it
enable_docker_service() {
    _infobox "Enabling Docker service to run on boot"
    rc-update add docker
    rc-service docker start

    # docker-in-docker requires the "tun" kernel module in order to work properly
    # as this module is not built-in into Alpine's stock kernel, we need to initialize
    # it on boot
    echo tun >> /etc/modules

    _complete_steps enable_docker_service welcome
}

welcome
install_essential_packages
setup_user
disable_mdev
enable_eudev
enable_seatd
enable_docker_service

_infobox "Post-installation finished!"
apk del alpine.sh
